version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka_server_container
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway_container
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  orders-service:
    build:
      context: ./orders
      dockerfile: Dockerfile
    container_name: orders_service_container
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - api-gateway
      - mongodb
      - rabbitmq
    restart: unless-stopped

  payments-service:
    build:
      context: ./payments
      dockerfile: Dockerfile
    container_name: payments_service_container
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - api-gateway
      - postgres
      - rabbitmq
      - orders-service
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: orders
      MONGO_INITDB_ROOT_PASSWORD: 12345

  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: payments
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_container
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  postgres_data: